services:
  ntopng:
    container_name: ntopng
    image: vimagick/ntopng
    network_mode: host
    command: --community -d /var/lib/ntopng -i enp1s0 -r 127.0.0.1:6379@0 -w 0.0.0.0:3003
    volumes:
      - $APPDATA/services/ntop/ntopng:/var/lib/ntopng
    restart: unless-stopped

  redis:
    container_name: ntopng-redis
    image: redis:alpine
    command: --save 900 1
    ports:
      - 6379:6379
    volumes:
      - $APPDATA/services/ntop/redis:/data
    restart: unless-stopped