services:
  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    networks:
#      - socket_proxy
      - server
    ports:
      - 8585:8080
    environment:
      TZ: 'America/New_York'
      PUID: 1000
      PGID: 1000
 #     DOCKER_HOST: tcp://socket-proxy:2375
      WATCHTOWER_MONITOR_ONLY: false
#      WATCHTOWER_ROLLING_RESTART: true
      WATCHTOWER_CLEANUP: true
      WATCHTOWER_INCLUDE_STOPPED: true
      WATCHTOWER_REVIVE_STOPPED: false
      WATCHTOWER_SCHEDULE: "0 1 0 * * *"
      WATCHTOWER_HTTP_API_TOKEN: tokenforhomepage
      WATCHTOWER_HTTP_API_METRICS: true
      WATCHTOWER_NOTIFICATION_URL: "discord://sartofCW6oCZwfhXT85PSTalYefCu6Uw0oemCsUrPweVkOQhdV2nw56fsQ4oQhNPoQfH@1235385758282547201"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped


# https://discord.com/api/webhooks/1235385758282547201/sartofCW6oCZwfhXT85PSTalYefCu6Uw0oemCsUrPweVkOQhdV2nw56fsQ4oQhNPoQfH
