services:
  homeassistant:
    image: lscr.io/linuxserver/homeassistant:latest
    container_name: homeassistant
    network_mode: host
    environment:
      PUID: 1000
      PGID: 1000
      TZ: America/New_York
      DOCKER_MODS: linuxserver/mods:homeassistant-hacs|linuxserver/mods:custom-mod2
    volumes:
      - $APPDATA/services/homeassistant:/config
      - /var/run/dbus:/var/run/dbus:ro
#    ports:
#      - 8123:8123 #optional
#    devices:
#      - /path/to/device:/path/to/device #optional
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
      - NET_RAW
