services:
  docker-gc:
    image: clockworksoul/docker-gc-cron:latest
    container_name: docker-gc
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
#    networks:
#      - socket_proxy
    volumes:
      - $APPDATA/services/docker-gc/docker-gc-exclude:/etc/docker-gc-exclude
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      CRON: 0 0 0 * * ? # Every day at midnight
      FORCE_IMAGE_REMOVAL: 1
      FORCE_CONTAINER_REMOVAL: 0
      GRACE_PERIOD_SECONDS: 604800
      DRY_RUN: 0
      CLEAN_UP_VOLUMES: 1
#      DOCKER_HOST: tcp://socket-proxy:2375
      TZ: 'America/New_York'
