services:
  dozzle:
    image: amir20/dozzle:latest
    container_name: dozzle
    networks:
#      - socket_proxy
      - server
    ports:
      - 8081:8080

    environment:
      TZ: 'America/New_York'
      PUID: 1000
      PGID: 1000
      DOZZLE_LEVEL: info
      DOZZLE_TAILSIZE: 300
      DOZZLE_FILTER: "status=running"
#      DOCKER_HOST: tcp://socket-proxy:2375
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
