services:
  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    networks:
      - server
    environment:
      TZ: 'America/New_York'
      PUID: 1000
      PGID: 1000
      LOG_LEVEL: ${LOG_LEVEL:-info}
      LOG_HTML: ${LOG_HTML:-false}
      CAPTCHA_SOLVER: ${CAPTCHA_SOLVER:-none}

    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
