services:
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    network_mode: service:gluetun

    environment:
      TZ: America/New_York
      PUID: 1000
      PGID: 1000
      UMASK_SET: 002
      WEBUI_PORT: 8181
      TORRENTING_PORT: 6881
    volumes:
      - $APPDATA/arr/qbittorrent:/config
      - $DATADIR/downloads:/data/downloads

    depends_on:
      gluetun:
        condition: service_healthy 
        restart: true

    healthcheck:
      test: "curl -sf https://example.com  || exit 1"
      interval: 1m
      timeout: 10s
      retries: 1
    labels: 
      - "deunhealth.restart.on.unhealthy=true"

    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
