services:
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    networks:
      - server
    ports:
      - 8989:8989
    environment:
      TZ: 'America/New_York'
      PUID: 1000
      PGID: 1000
    volumes:
      - $APPDATA/arr/sonarr:/config
      - $MEDIADIR/tv:/data/media/tv
      - $MEDIADIR2/tv:/data/media/tv2
      - $MEDIADIR3/tv:/data/media/tv3
      - $DATADIR/downloads:/data/downloads

    security_opt:
      - no-new-privileges:true
    restart: "unless-stopped"

  sonarr-anime:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr-anime
    networks:
      - server
    ports:
      - 8787:8989

    environment:
      TZ: 'America/New_York'
      PUID: 1000
      PGID: 1000
    volumes:
      - $APPDATA/arr/sonarr-anime:/config
      - $MEDIADIR/anime:/data/media/anime
      - $MEDIADIR2/anime:/data/media/anime2
      - $MEDIADIR3/anime:/data/media/anime3
      - $DATADIR/downloads:/data/downloads

    security_opt:
      - no-new-privileges:true
    restart: "unless-stopped"
